/* Local preview only: no network requests or persistent storage. */
const menu = document.querySelector('.menu-button');
const navigation = document.querySelector('#site-nav');
function closeMenu() { menu.setAttribute('aria-expanded','false'); menu.setAttribute('aria-label','Open navigation'); navigation.classList.remove('is-open'); }
menu.addEventListener('click',()=>{ const open=menu.getAttribute('aria-expanded')!=='true'; menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close navigation':'Open navigation');navigation.classList.toggle('is-open',open); });
navigation.addEventListener('click',event=>{if(event.target.closest('a'))closeMenu();});
document.addEventListener('keydown',event=>{if(event.key==='Escape' && menu.getAttribute('aria-expanded')==='true'){closeMenu();menu.focus();}});
const tabs=[...document.querySelectorAll('[data-audience]')];
function selectAudience(tab){tabs.forEach(item=>{const selected=item===tab;item.setAttribute('aria-selected',selected);item.tabIndex=selected?0:-1;document.getElementById(item.getAttribute('aria-controls')).hidden=!selected;});}
tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>selectAudience(tab));tab.addEventListener('keydown',event=>{let next;if(event.key==='ArrowRight')next=tabs[(i+1)%tabs.length];if(event.key==='ArrowLeft')next=tabs[(i+tabs.length-1)%tabs.length];if(event.key==='Home')next=tabs[0];if(event.key==='End')next=tabs.at(-1);if(next){event.preventDefault();selectAudience(next);next.focus();}});});
document.querySelectorAll('[data-plan]').forEach(button=>button.addEventListener('click',()=>{document.querySelector('#contact-plan').value=button.dataset.plan;document.querySelector('#form-status').textContent='';location.hash='contact';document.querySelector('#contact-name').focus({preventScroll:true});}));
const form=document.querySelector('#contact-form');
form.addEventListener('submit',event=>{event.preventDefault();let firstInvalid;for(const key of ['name','email','city']){const field=document.getElementById(`contact-${key}`);const valid=field.value.trim()!=='' && field.validity.valid;field.setAttribute('aria-invalid',String(!valid));document.getElementById(`${key}-error`).hidden=valid;if(!valid && !firstInvalid)firstInvalid=field;}const status=document.querySelector('#form-status');if(firstInvalid){status.textContent='Please check the highlighted fields.';firstInvalid.focus();return;}status.textContent=`Thanks, ${document.querySelector('#contact-name').value.trim()}. Your ${document.querySelector('#contact-plan').value.toLowerCase()} enquiry looks ready. This preview has not sent your details or booked a call.`;});
form.addEventListener('input',event=>{const key=event.target.name;if(['name','email','city'].includes(key) && event.target.validity.valid && event.target.value.trim()){event.target.setAttribute('aria-invalid','false');document.getElementById(`${key}-error`).hidden=true;}document.querySelector('#form-status').textContent='';});
