const source=window.BoringLibraryData.source;
const token=path=>path.split('.').reduce((a,k)=>a[k],source);
const css=path=>`var(--boring-${path.replaceAll('.','-')})`;
const resolve=value=>typeof value==='string'&&/^\{.+\}$/.test(value)?resolve(token(value.slice(1,-1)).$value):value;
const label=path=>{const t=token(path),v=resolve(t.$value);return t.$type==='color'?v.hex||'Colour':typeof v==='object'&&v.unit?`${v.value}${v.unit}`:String(v);};
const main=document.querySelector('#examples'), kind=document.body.dataset.kind, paths=document.body.dataset.tokens.split(',').filter(Boolean);
const brand=()=>'<img src="../assets/little-b/little-b-daylight.svg" alt="Little b">';
const sample=(p,preview)=>`<div class="sample">${preview}<small>${p}</small><code>${label(p)}</code></div>`;
if(kind==='colors')main.innerHTML=paths.map(p=>sample(p,`<div class="swatch" style="background:${css(p)}"></div>`)).join('');
else if(kind==='type')main.innerHTML=paths.map(p=>`<div class="type-row"><p style="font:${css(p)};letter-spacing:var(--boring-${p.replaceAll('.','-')}-letter-spacing)">A little care. More life.</p><small>${p}</small></div>`).join('');
else if(kind==='radius'||kind==='shadow')main.innerHTML=paths.map(p=>sample(p,`<div class="tile" style="${kind==='radius'?'border-radius':'box-shadow'}:${css(p)}">${kind==='radius'?label(p):'Aa'}</div>`)).join('');
else if(kind==='space')main.innerHTML=paths.map(p=>sample(p,`<div class="bar" style="width:${css(p)}"></div>`)).join('');
else if(kind==='brand'||kind==='motion')main.innerHTML=`<div class="brand-panel">${brand()}<span>Little b · still</span></div><div class="brand-panel" style="background:var(--boring-palette-sky)"><img class="boring-loader" src="../assets/little-b/little-b-daylight.svg" alt="Little b waiting"><span>Gentle settle · reduced motion respected</span></div>`;
else if(kind==='wordmark')main.innerHTML=`<div class="brand-panel">${brand()}<span class="ds-wordmark">boring</span></div><div class="brand-panel" style="background:var(--surface-inverse);color:var(--text-on-inverse)">${brand()}<span class="ds-wordmark">boring</span></div>`;
else if(kind==='welcome')main.innerHTML=`<div class="brand-panel" style="background:var(--boring-palette-sky)">${brand()}<h2 style="font-size:26px">A good day for the everyday.</h2></div>`;
else if(kind==='status')main.innerHTML=['success','attention','error','info'].map(name=>`<div class="tile" style="border:0;border-radius:12px;color:var(--boring-color-status-${name}-foreground);background:var(--boring-color-status-${name}-background)">${{success:'Visit confirmed',attention:'Review needed',error:'Check this field',info:'Report ready'}[name]}</div>`).join('');
else if(kind==='states')main.innerHTML='<button class="preview-button">Hover or focus me</button><button class="preview-button" style="background:var(--boring-color-action-pressed)">Pressed</button><button class="preview-button" disabled>Disabled</button>';
else if(kind==='targets')main.innerHTML='<button class="preview-button">48 px minimum</button><button class="preview-button" style="min-height:56px;font-size:19px">56 px for parents</button>';
else if(kind==='card')main.innerHTML='<article class="demo-card"><span class="ds-label">Your next visit</span><h2>A little care, at home.</h2><p>Tuesday · 7–9 am<br>We’ll call the evening before.</p></article>';
else if(kind==='bilingual')main.innerHTML='<div><p style="font:var(--boring-typography-body-parent)">A little care, every day.</p><p lang="hi" data-lang="hi" style="font-size:24px">हर दिन, थोड़ी देखभाल।</p><small>Language and translated layouts require review with native speakers.</small></div>';
else if(kind==='numbers')main.innerHTML='<div><span class="ds-label">Next visit</span><p class="ds-num" style="font-size:32px;margin:8px 0">22 Sep · 7–9 am</p><small>Keep units and context next to the value.</small></div>';
